src/SecureBank/Controllers/PortalSearchController.cs
using SecureBank.Helpers.Authorization.Attributes;
using Microsoft.AspNetCore.Mvc;
using SecureBank.Interfaces;
using SecureBank.Models.PortalSearch;

namespace SecureBank.Controllers
{
    [AuthorizeNormal(AuthorizeAttributeTypes.Mvc)]
    public class PortalSearchController : MvcBaseContoller
    {
        private readonly IPortalSearchBL _portalSearchBL;

        public PortalSearchController(IPortalSearchBL portalSearchBL)
        {
            _portalSearchBL = portalSearchBL;
        }

        [HttpGet]
        public IActionResult Index(string searchString)
        {
            PortalSearchModel portalSearchModel = _portalSearchBL.Search(searchString);

            return View(portalSearchModel);
        }
    }
}

src/SecureBank/Controllers/StoreController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using SecureBank.Helpers.Authorization.Attributes;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SecureBank.Helpers;
using SecureBank.Interfaces;
using SecureBank.Models.Store;

namespace SecureBank.Controllers
{
    [AuthorizeNormal(AuthorizeAttributeTypes.Mvc)]
    public class StoreController : MvcBaseContoller
    {
        private readonly IStoreBL _storeBL;

        public StoreController(IStoreBL storeBL)
        {
            _storeBL = storeBL;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            List<StoreItem> storeItems = await _storeBL.GetStoreItems();

            return View(storeItems);
        }

        [HttpGet]
        public async Task<IActionResult> ItemDetails([FromQuery] int itemId)
        {
            StoreItem storeItems = await _storeBL.GetStoreItem(itemId);

            return View(storeItems);
        }

        [HttpGet]
        public async Task<IActionResult> History()
        {
            List<PurcahseHistoryItemResp> purchasedItems =
                await _storeBL.GetPurchaseHistory(HttpContext.GetUserName());

            return View(purchasedItems);
        }
    }
}

src/SecureBank/Controllers/TransactionController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SecureBank.Helpers.Authorization.Attributes;
using SecureBank.DAL.DBModels;
using SecureBank.DAL;
using SecureBank.Interfaces;
using SecureBank.Helpers;
using SecureBank.Filters;

namespace SecureBank.Controllers
{
    [AuthorizeNormal(AuthorizeAttributeTypes.Mvc)]

    public class TransactionController : MvcBaseContoller
    {
        private readonly PortalDBContext _context;

        private readonly ITransactionBL _transactionBL;

        public TransactionController(PortalDBContext context, ITransactionBL transactionBL)
        {
            _context = context;

            _transactionBL = transactionBL;
        }

        // GET: Transaction
        public IActionResult Index()
        {
            string viewName = _transactionBL.GetIndexViewName();

            return View(viewName);
        }

        // GET: Transaction/Details/5
        public IActionResult Details(int? id)
        {
            TransactionDBModel transaction = _transactionBL.Details(id);
            if (transaction == null)
            {
                return NotFound();
            }

            return View(transaction);
        }

        // GET: Transaction/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Transaction/Create
        // To protect from over posting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,SenderId,ReceiverId,TransactionDateTime,Reason,Amount,Reference")] TransactionDBModel transaction)
        {
            if (!ModelState.IsValid)
            {
                return View(transaction);
            }

            bool createResult = _transactionBL.Create(transaction);
            if (!createResult)
            {
                ModelState.AddModelError(string.Empty, "Error");
                return View(transaction);
            }

            return RedirectToAction(nameof(Index));
        }

        // GET: Transaction/Edit/5
        [UnknownGeneration]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var transactionTable = await _context.Transactions.FindAsync(id);
            if (transactionTable == null)
            {
                return NotFound();
            }

            return View(transactionTable);
        }

        // POST: Transaction/Edit/5
        // To protect from overpoting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [UnknownGeneration]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,SenderId,ReceiverId,TransactionDateTime,Reason,Amount,Reference")] TransactionDBModel transactionTable)
        {

            if (id != transactionTable.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(transactionTable);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TransactionTableExists(transactionTable.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(transactionTable);
        }

        [UnknownGeneration]
        // GET: Transaction/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var transactionTable = await _context.Transactions
                .FirstOrDefaultAsync(m => m.Id == id);
            if (transactionTable == null)
            {
                return NotFound();
            }

            return View(transactionTable);
        }

        // POST: Transaction/Delete/5
        [UnknownGeneration]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var transactionTable = await _context.Transactions.FindAsync(id);
            _context.Transactions.Remove(transactionTable);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TransactionTableExists(int id)
        {
            return _context.Transactions.Any(e => e.Id == id);
        }
    }
}

src/SecureBank/Views/Shared/_Layout.cshtml
@using SecureBank.Helpers

<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- awesome fonts cs-->
    <link href="/css/font-awesome.css" rel="stylesheet" type="text/css">
    <!-- owl carousel css-->
    <link rel="stylesheet" href="/owl-carousel/assets/owl.carousel.min.css" type="text/css">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <!-- custom CSS -->
    <link rel="stylesheet" href="/css/style.css">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/popup.css" />

    @RenderSection("Styles", required: false)
    <title>SecureBank</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light bg-transparent" id="gtco-main-nav">
        <div class="container">
            <a class="navbar-brand">SecureBank</a>
            <button class="navbar-toggler" data-target="#my-nav" onclick="myFunction(this)" data-toggle="collapse">
                <span class="bar1"></span> <span class="bar2"></span> <span class="bar3"></span>
            </button>
            <div id="my-nav" class="collapse navbar-collapse">
                @if (!Context.IsAuthenticated())
                {
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="#services">Services</a></li>
                        <li class="nav-item"><a class="nav-link" href="#about">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="#news">News</a></li>
                    </ul>
                }
                else
                {
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li class="nav-item"><a class="nav-link" asp-controller="Transaction" asp-action="Index">Transactions</a></li>
                        <li class="nav-item"><a class="nav-link" asp-controller="Store" asp-action="Index">Store</a></li>
                        <li class="nav-item"><a class="nav-link" asp-controller="PortalSearch" asp-action="Index">Search</a></li>

                    </ul>
                }

                @if (!Context.IsAuthenticated())
                {
                    <form class="form-inline my-2 my-lg-0">
                        <a href="/auth/login" id="mainLoginButton" class="btn btn-primary my-2 my-sm-0 mr-3 text-uppercase">login</a>
                        <a href="/auth/register" id="mainSignUpButton" class="btn btn-primary my-2 my-sm-0 text-uppercase">
                            sign up
                        </a>
                    </form>
                }
                else
                {
                    <div class="pull-right">
                        <img style="border-radius:50%" src="/api/User/ProfileImage?user=@Context.GetUserName()" height="50" width="50" />
                        <span style="color:gray">@Context.GetUserName()</span>
                        <span class="navAccountAmountColor">
                            <span id="amount"></span>
                            <span>€</span>
                        </span>
                    </div>
                    <script>
                    let username = "@Context.GetUserName()";
                    </script>
                    <form class="form-inline my-2 my-lg-0">
                        <a class="btn btn-primary my-2 my-sm-0 text-uppercase" href="/auth/Logout?returnUrl=/">Logout</a>
                    </form>
                }

            </div>
        </div>
    </nav>
    @RenderBody()
    <footer class="container-fluid" id="gtco-footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="row">
                        <div class="col-12">
                            <p>&copy; 2022. SSRD SecureBank</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>


    <script src="/js/popper.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <!-- owl carousel js-->
    <script src="/owl-carousel/owl.carousel.min.js"></script>
    <script src="/js/main.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="/js/chart-js/chart.js"></script>
    @RenderSection("Scripts", required: false)
    <script>

        $(document).ready(function () {
            @if (Context.IsAuthenticated())
            {
                <text>
                        $.get("/api/User/GetAvailableFunds?user=@Context.GetUserName()", function(data) {
                            $("#amount").html(data.balance);
                        });
                </text>
            }
            else
            {
                <text>
                    if (window.location.pathname == '/') {
                        document.getElementById("mainLoginButton").classList.add('btn-outline-dark');
                        document.getElementById("mainSignUpButton").classList.add('btn-info');
                    }
                </text>
            }

            if (window.location.pathname == '/') {
                // Index (home) page
                document.getElementById("gtco-main-nav").classList.add('mainBuble');
            }
        });

    </script>
</body>
</html>

src/SecureBank/Views/Shared/_LayoutFirstPage.cshtml
@using SecureBank.Helpers

<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- awesone fonts css-->
    <link href="/css/font-awesome.css" rel="stylesheet" type="text/css">
    <!-- owl carousel css-->
    <link rel="stylesheet" href="/owl-carousel/assets/owl.carousel.min.css" type="text/css">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <!-- custom CSS -->
    <link rel="stylesheet" href="/css/style.css">
    <title>SecureBank</title>
    <style>
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light bg-transparent" id="gtco-main-nav">
        <div class="container">
            <a class="navbar-brand">SecureBank</a>
            <button class="navbar-toggler" data-target="#my-nav" onclick="myFunction(this)" data-toggle="collapse">
                <span class="bar1"></span> <span class="bar2"></span> <span class="bar3"></span>
            </button>
            <div id="my-nav" class="collapse navbar-collapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="#services">Services</a></li>
                    <li class="nav-item"><a class="nav-link" href="#about">About</a></li>
                    <li class="nav-item"><a class="nav-link" href="#news">News</a></li>
                </ul>

                @if (!User.Identity.IsAuthenticated)
                {
                    <form class="form-inline my-2 my-lg-0">
                        <a href="/auth/login" class="btn btn-outline-dark my-2 my-sm-0 mr-3 text-uppercase">login</a>
                        <a href="/auth/register" class="btn btn-info my-2 my-sm-0 text-uppercase">
                            sign up
                        </a>
                    </form>
                }
                else
                {
                    <div class="pull-right">
                        <img src="/user/ProfileImage?user=@User.Identity.Name" height="50" width="50" />
                        <span style="color:gray">@User.Identity.Name</span>
                        <span class="navAccountAmountColor">
                            <span id="amount"></span>
                            <span>€</span>
                        </span>
                    </div>
                    <script>
                    let username = "@User.Identity.Name";
                    </script>
                    <a class="btn btn-info my-2 my-sm-0 text-uppercase" href="/Identity/Account/Logout?returnUrl=/">Logout</a>
                }

            </div>
        </div>
    </nav>
    @RenderBody()
    <footer class="container-fluid" id="gtco-footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="row">
                        <div class="col-12">
                            <p>&copy; 2020. SSRD SecureBank </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>


    <script src="/js/popper.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <!-- owl carousel js-->
    <script src="/owl-carousel/owl.carousel.min.js"></script>
    <script src="/js/main.js"></script>

    <script src="/js/chart-js/chart.js"></script>
    @RenderSection("Scripts", required: false)
    <script>

        $(document).ready(function() {
            $.get("/user/GetAvailableFunds/@Context.GetUserName()", function(data) {
                $("#amount").html(data);
                });
            });

    </script>
</body>
</html>